'use strict';

const { countSummary } = require('../runmeta');
const { friendlyBytes, isoNow } = require('../format');

function responsePreview(response) {
  if (!response) return 'no response recorded';
  const header = [];
  if (response.status !== undefined && response.status !== null) header.push(`HTTP ${response.status}`);
  if (typeof response.body === 'string' && response.body.length > 0) {
    const kind = response.bodyEncoding === 'base64' ? 'base64 payload' : 'body';
    header.push(`${friendlyBytes(response.body.length)} ${kind}`);
  } else {
    header.push('empty body');
  }
  return header.join(' · ');
}

function escapeMd(input) {
  return String(input === null || input === undefined ? '' : input).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function buildMarkdown(run) {
  const summary = countSummary(run);
  const lines = [];

  const status = run.status === 'SUCCESS' || run.status === 'PASSED' ? 'PASSED' : 'FAILED';
  lines.push(`# API Hub run report`);
  lines.push('');
  lines.push(`**${run.name || 'request'}** — **${status}** (${summary.passed}/${summary.total} checks passed)`);
  lines.push('');

  lines.push('| Field | Value |');
  lines.push('| --- | --- |');
  lines.push(`| Run | ${escapeMd(run.id || '—')} |`);
  if (run.name) lines.push(`| Request | ${escapeMd(run.name)} |`);
  if (run.trigger) lines.push(`| Trigger | ${escapeMd(run.trigger)} |`);
  lines.push(`| Status | ${escapeMd(status)} |`);
  if (run.statusCode !== null && run.statusCode !== undefined) {
    lines.push(`| HTTP status | ${run.statusCode} |`);
  }
  if (run.durationMs !== null && run.durationMs !== undefined) {
    lines.push(`| Duration | ${run.durationMs} ms |`);
  }
  lines.push(`| Response | ${escapeMd(responsePreview(run.response))} |`);
  if (run.error) lines.push(`| Error | \`${escapeMd(run.error)}\` |`);
  lines.push('');

  if (run.request && run.request.url) {
    lines.push('## Request');
    lines.push('');
    lines.push(`\`${run.request.method || 'GET'} ${escapeMd(run.request.url)}\``);
    lines.push('');
  }

  lines.push('## Checks');
  lines.push('');
  if (run.testCases.length === 0) {
    lines.push('_No assertions configured for this request._');
    lines.push('');
  } else {
    lines.push('| Check | Result |');
    lines.push('| --- | --- |');
    for (const tc of run.testCases) {
      lines.push(`| ${escapeMd(tc.name)} | ${tc.passed ? 'PASS' : 'FAIL'} |`);
    }
    lines.push('');
  }

  const failed = run.testCases.filter((t) => !t.passed);
  if (failed.length > 0) {
    lines.push('## Failures');
    lines.push('');
    for (const tc of failed) {
      lines.push(`- **${escapeMd(tc.name)}**`);
      if (tc.detail) lines.push(`  \`\`\`\n  ${String(tc.detail).replace(/\n/g, '\n  ')}\n  \`\`\``);
    }
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`_Generated by apihub at ${isoNow()}_`);
  lines.push('');
  return lines.join('\n');
}

module.exports = { buildMarkdown };
