'use strict';

// ---------------------------------------------------------------------------
// `mockshift.json` — the per-app configuration file (a drop-in analogue of
// google-services.json). Generated by the MockShift portal when you create an
// SDK token, it carries the token, endpoint and discovery options so the app
// only needs:
//
//     const { attach } = require('mockshift-sdk');
//     attach(app);            // loads ./mockshift.json automatically
//
// Lookup order (first found wins):
//   1. an explicit path passed to loadConfigFile(path) / attach(app, { configFile })
//   2. process.env.MOCKSHIFT_CONFIG
//   3. ./mockshift.json
//   4. ./mockshift.config.json
//   5. ./.mockshift/mockshift.json
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const { MockshiftConfigError } = require('./errors');

const FILENAMES = ['mockshift.json', 'mockshift.config.json', path.join('.mockshift', 'mockshift.json')];

function candidatePaths(explicitPath, cwd = process.cwd(), env = process.env) {
  const out = [];
  if (explicitPath) out.push(path.resolve(cwd, explicitPath));
  if (env.MOCKSHIFT_CONFIG) out.push(path.resolve(cwd, env.MOCKSHIFT_CONFIG));
  for (const name of FILENAMES) out.push(path.join(cwd, name));
  return out;
}

function findConfigPath(explicitPath, cwd = process.cwd(), env = process.env) {
  for (const candidate of candidatePaths(explicitPath, cwd, env)) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

// Parse JSON, tolerating a UTF-8 BOM (the portal writes plain UTF-8, but
// editors on Windows sometimes add one).
function parseConfig(text, source) {
  const clean = text.replace(/^\uFEFF/, '');
  try {
    const parsed = JSON.parse(clean);
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      throw new Error('root must be a JSON object');
    }
    return parsed;
  } catch (err) {
    throw new MockshiftConfigError(`Invalid mockshift config at ${source}: ${err.message}`);
  }
}

// Load and normalize the config file. Returns null when none exists.
function loadConfigFile(explicitPath, deps = {}) {
  const cwd = deps.cwd || process.cwd();
  const env = deps.env || process.env;
  const found = findConfigPath(explicitPath, cwd, env);
  if (!found) return null;
  const raw = fs.readFileSync(found, 'utf8');
  const config = parseConfig(raw, found);
  config.__path = found;
  return config;
}

module.exports = { loadConfigFile, findConfigPath, parseConfig, candidatePaths, FILENAMES };
